"""base64-encoded images for GUI."""
from wx.lib.embeddedimage import PyEmbeddedImage

# Icon
camera = PyEmbeddedImage("""
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
jwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41
LjEwMPRyoQAAAqlJREFUWEfV1kuoTWEUwPHtUQiJdMkrA3nNqFtKURgpjwllYqCUgUyMMJAyUOqa
MFSKMvAaIFEmEjGjPMuAiSSSV3n7/0/703d2a5+z0z1HVv26t3XW3t/e33MX/1usw2XcbOAgpmLY
Yi5e4FdDX7EfjWM81mB9aTnGwvDvMfxA1Fid95iDrjEC2/AB6eKX2Ai7cQXeIL95U0cxHVMwAaPQ
FiY24xFe4yTO4TOiG/4t73cHBzALf8LGbdiirRgHn/Rwmav6hvs4grVYUFqKXbiEt/iJ6PrvuIVB
tOIG0o+zTZSxAfmF8i2GYJ3DFoXzxTlkj1avz13HTBRfyoR8K8fLBi6UucRechnmMQlLSvMwEimm
4Szye+Sc0PvQlvQN7d6HcBml/EfsRJpAA9gLx/R56SlOYxlSnQ9hT9QNx22EP1T5JmNg2PhVOJZR
7StsQnoIh8M5EdX6wuEPOdfyShh2uauk7o0SH8KeMJwT1xDVKUzm7ObWZCFW4R2iuiqHI80JV0dU
ozCZO4XRMA4hqok4J5yYhks0qlGYzB1HCv+PaiKeG64Ow30iqlGYzP3zB7iIiTC2o+mBdBdOWsMd
M6pRmMw9w0IYi/AAUV3OJboHhjumG1xUpzCZ82Y7kGILPA+iWrlE3Scmw3BXvYeoVmGy6gnmw3BF
+BD2RHU4XKIn4GaVwrMj31WrwmSVDZ1HeivD4XBOODHlEl0NT1LDndCzo9uxHibr+BCpJzqF27Zn
RzrmOwmTdeyJx3BOODHT6jAcmhlw2z4DD7DoHlVhshsnpqvDJZqGwB3TbduzI7qmTpjspzDZT8Wn
SqKfbLvtm7DfbLvYjU47W6+4Odl262PDrTMq6qUr8JuxFYthotOWOVxsw7Zssy18GrvEcenFxPSe
3ts2yjcvit8pQvHdFXnBrAAAAABJRU5ErkJggg==""")

camera_to_pdf_blue = PyEmbeddedImage("""
iVBORw0KGgoAAAANSUhEUgAAASwAAABoCAMAAAB8HT2JAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
jwv8YQUAAAMAUExURQAAAIfY/4rZ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALVsY8kAAAEAdFJOU///////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////wBT9wclAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGnRFWHRT
b2Z0d2FyZQBQYWludC5ORVQgdjMuNS4xMDD0cqEAAAWMSURBVHhe7dBbduQgDEXRdOY/5zSIY8xD
2KIDuJab/eNCCETdr5/N7OVh/enDqRZrWNx2gcbPwtvMONZgDIu7LtH6UXiaHed0trC46QbNn4SX
deCgyhQW99yi/YPwsB6c1FjC4hYDDnwO3mUU2jmq2GEl6OdszRCWXGDEkY/Bs4yOA+FsbYeViCfk
bC0JS9pAyaNixKFPwauMziPyq3KGJU0RRYeCEYc+Ba8ySs6En4UYlrQkKHeO+7S0eJRReojfmR1W
gkPNtJph/Rr3Pou3GHGomdYRlmyPxt0P4iFGHHKKJUJYsudliwHk9gfxDCMOeeVaSFiy40jFYTkE
Vz6ERxhxSFQFx4cldSdUPAo6egSlK3Q+gzcYcSioKz4sqXqUHAoKGhJstNH3CJ5gxCHUpSQsKoJS
gc0K2y10PYEXGHHoUNW+zvuoCEoZtlS0NND0AB5gxKGoLJrDYqOJNh096zHfiEOnovola0FFUDpR
v0Cjipb1mG/EoUReTsJKeimcqF+iVUXLcow34lAqq9vConyDZg0dyzHeiEOZdCMNKzazjCjfol1D
x2pMN+JQLtnJwgpFfp6kMUHZoRBRVtCwGtONOFQ4t4qwNNIXUYwog2KN/dWYbsShUty7D0v6D9Qy
bAXUauwvxnAjDlWOzduwQjuoFdgMqFXYXozhRhyqsdsTFhUFDR6VCtuLMXyI+7AY6lFR0eJRKbG7
GMOH6AmLQgNNDoUSu4sxfIjbsJjpUWmgyaNSYHMxhg/RERaFJtocCgU2F2P4EPawWF+g0aGQY28x
hg9xFxYjHQoXaHQo5Nib5VsfwPAhzGGxvkTrI2F9NyaE2WO8JqzWCKkPchMWEx0Kl2h1KGTYmqUx
Q8qDWMNifYPmR8JqpCXVQV4Ulp6WFAd5U1hqWlIb5FVhaWlJaZB3haWkJZVBXhZWnZYUBnlbWFVa
sh7kdWGVaclykPeFJbP56cjoQZ4Ii/VczNKG5Tv56vKZ1rBM/5BWh0KGLdtVv8Ys9S8f8qWsLp95
E9bV0RqtjWb2bFf9GrPUvxwpy6tn/qdh8Tm+5yf5UTOH1bogQaNDIcee5aYBmKUMO6p8i2X8Ku7C
krOC9QUaHQo59iaTUd8sHFlnjirfYhm/CntYrRsi2hwKBTbnkklJVspbYjV802W2rnWE1boCNHlU
CmxOJYPSrJS3xGr4pstsXbsNSw4HFBpociiU2J1J5mRZKY85qnyPZbWu9YTVukPQ4lEpsTuRjMmz
Uh5zVPkey2pduw9LToOKggaPSoXteWRKkZXyGqrH5vFN60KKmb6wtBs8NgNqFbankSFlVupfjo5l
rPMRUswYwkpv164wNAj2Z5EZVVbqX8a5TH/4j5BixhLWeV5QjCiDooKGSWREnZX6l4Nkmf6I65op
rHj/gbJDIaKsoWMSP0HJSnlQUY1LfsR1zRaW3GBBu4qWWfSslBcV1bjkR1zXjGHJFfdo1tEzjZqV
8qSiGpd8i+2UNSy54w6tDTQtxvBEUT2W5VdhDksuuUZjC12LMTxRVI9l+VXYw5JbrtDWRNtiDE8U
VZaxGn/UOsIK97TQcoHGxRieKKrSJc51+FXpCqv9h9m+ROtiDE8UVenykjU/S51h6X+ZrRs0L8bw
RFGVLodluZ3qDsuTy0HJgAOLMXyIfwrr3/D6xRg+xA6rww6rww6rww6rww6rww6rww6rww6rww6r
ww6rww6rww6rgwtr6H1tPH41pg+xw+qww+rgw1qSFm9fjvFD7LA6SFgL0govfwDzh9hhdQhhTU9L
3v0IHjAEYU1OS0Y8gxcMcYQ1Na0w4Rk8YYgY1sS0GPAM3jDEGda0tLj+ITxiiCSsOXFx9WN4xhBZ
WOPj4toH8ZAhirAcNgbgwjcpw9ou7LDMfn7+AosDRBYaOzfgAAAAAElFTkSuQmCC""")
